import React from 'react';
import { Server, Settings, Smartphone, QrCode, ArrowRight, BookOpen } from 'lucide-react';

export function Documentation() {
  const steps = [
    {
      icon: Server,
      title: 'Step 1: System Deployment',
      description: 'Host the MDM bridge and ensure secure network access.',
      details: [
        'Deploy this application to a secure, compliant cloud environment (e.g., Google Cloud Run, AWS Fargate).',
        'Configure network ingress to only allow traffic over TLS 1.2+ (HTTPS) to satisfy ISO 27001 data-in-transit requirements.',
        'Ensure environment variables (e.g., SIEM API keys, Database URIs) are securely injected via a secret manager, not hardcoded.'
      ]
    },
    {
      icon: Settings,
      title: 'Step 2: SIEM Setup & Configuration',
      description: 'Connect the bridge to your centralized logging platform.',
      details: [
        'Navigate to the "SIEM Integration" tab in this application.',
        'Select your SIEM provider (e.g., Splunk, QRadar, Elastic).',
        'Enter your organization\'s HTTP Event Collector (HEC) URL or Logstash endpoint.',
        'Provide the secure API token/key. Click "Save Configuration" and verify the status changes to "Connected".'
      ]
    },
    {
      icon: Smartphone,
      title: 'Step 3: Add an Honor Phone (Device Enrollment)',
      description: 'Provision a device and install the HonorGuard agent.',
      details: [
        'Factory reset the target Honor smartphone.',
        'Tap the welcome screen 6 times to trigger the hidden QR code reader for Android Enterprise provisioning.',
        'Scan the MDM Enrollment QR Code generated by your central device management policy.',
        'The device will automatically download the HonorGuard MDM profile, lock down unauthorized settings, and appear in the "Honor Fleet" tab.',
        'Event logs (system, auth, app) will immediately begin streaming to your SIEM.'
      ]
    }
  ];

  return (
    <div className="p-8 space-y-8 animate-in fade-in duration-500 max-w-4xl">
      <header className="mb-8 border-b border-slate-800 pb-6">
        <div className="flex items-center gap-3 mb-2">
          <BookOpen className="w-8 h-8 text-emerald-400" />
          <h2 className="text-3xl font-display font-semibold text-white">System Documentation</h2>
        </div>
        <p className="text-slate-400 mt-1">Official guide for deploying the Honor MDM Bridge, configuring the SIEM, and enrolling devices securely.</p>
      </header>

      <div className="space-y-6">
        {steps.map((step, index) => (
          <div key={index} className="bg-slate-900 border border-slate-800 rounded-xl p-6 flex gap-6 relative overflow-hidden">
            <div className="absolute top-0 left-0 w-1 h-full bg-emerald-500/50"></div>
            
            <div className="flex-shrink-0 pt-1">
              <div className="w-12 h-12 rounded-lg bg-slate-950 border border-slate-800 flex items-center justify-center text-emerald-400">
                <step.icon className="w-6 h-6" />
              </div>
            </div>
            
            <div className="flex-1">
              <h3 className="text-xl font-medium text-white mb-2">{step.title}</h3>
              <p className="text-sm text-slate-400 mb-4">{step.description}</p>
              
              <div className="bg-slate-950 rounded-lg p-5 border border-slate-800/50">
                <ul className="space-y-3">
                  {step.details.map((detail, idx) => (
                    <li key={idx} className="flex gap-3 text-sm text-slate-300 items-start">
                      <ArrowRight className="w-4 h-4 text-emerald-500 mt-0.5 flex-shrink-0" />
                      <span className="leading-relaxed">{detail}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="mt-8 bg-amber-500/10 border border-amber-500/20 rounded-xl p-6 flex gap-4">
        <QrCode className="w-8 h-8 text-amber-400 flex-shrink-0" />
        <div>
          <h4 className="text-sm font-medium text-amber-400 uppercase tracking-wider mb-1">Testing Enrollment</h4>
          <p className="text-sm text-amber-400/80 leading-relaxed">
            For isolated testing purposes before production rollout, you can manually sideload the HonorGuard agent APK via ADB: <code className="bg-amber-500/20 px-1.5 py-0.5 rounded text-amber-300 mx-1 font-mono text-xs">adb install -r honorguard_agent_v2.apk</code> followed by setting the device owner profile.
          </p>
        </div>
      </div>
    </div>
  );
}
